### ISSUE TITLE
Travis builds will not run correctly

### ISSUE THREAD

**Issue by jcmnn** [feliwir/benny#4]
Currently, Travis builds will not handle interrupts correctly.
I assume it's a problem with the version of clang used in Travis (3.8) being old.

    arch/x86_64/../x86_shared/idt.cpp:8:16: warning: unknown attribute 'interrupt'

          ignored [-Wunknown-attributes]

    __attribute__((interrupt)) void Exception_DivByZero(InterruptFrame *frame) {

                   ^

The interrupt functions won't have the necessary register state saving and iret so they'll cause the kernel to crash when returning.

**Comment by feliwir** [comment]
I will see if i can update travis to use 4.0 once i am home.

**Comment by feliwir** [comment]
So i finally were able to check. LLVM does not support newer precise packages anymore:
https://apt.llvm.org/

Unfortunaly it also doesn't look like Travis will add support for any newer Ubuntu version soon. Till that point it is probably most easy to use 3.8 for CI. Until then I'll close this issue
